# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b07c3b073174b4dbb79b39742eb87fe98ca727535caf60cf29b1a6e51eab1cf7eb642820bece45997064c5dc8ba20a7cc92debabe8441a029cf77116767febf2

test:
  secret_key_base: 652d4f5437fc56a43ef6b79b8784375f6186eae9d7b672aae2321cff849390108d3bbc5b97d9be10e1951d595257a871e8fc4026808ae0dcb3f08a2e45395904

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
